.TH "dotd" "1" "04 April 2021" "dotd" "Configuration manager"

.SH NAME
.B dotd
- a helper for management of flat configuration files


.SH SYNOPSIS
.B dotd
.RI [ OPTION "]... [" FILE "]"


.SH DESCRIPTION
.B dotd
is a simple administrative utility for dynamic generation of flat configuration
files from a
.I *.d
directory.

Ideally, every configuration would implement inclusion of configuration
overrides that could be shipped using a package manager or manipulated from
shell scripts. But since this is not always the case, it is sometimes needed
to simulate the same behaviour in another way. This program does the task:
it moves the original configuration file into a
.I *.d
directory, alongside other fragment files, and then rewrites the original file
by the contents of all fragment files concatenated together.

The program does
.I not
watch the fragment files for changes so it has to be instructed manually to
regenerate the configuration.


.SH OPTIONS
.B \-i
.IR FILE ,
.B \--install
.I FILE
.RS 4
Convert the
.I FILE
into a dynamically generated one.
.RE

.B \-r
.IR FILE ,
.B \--restore
.I FILE
.RS 4
Restore the original flat
.IR FILE .
.RE

.B \-u
.IR FILE ,
.B \--update
.I FILE
.RS 4
Regenerate the given configuration
.IR FILE .
.RE

.B \-t
.IR FILE ,
.B \--test
.I FILE
.RS 4
Check whether the
.I FILE
is managed by the program.
.RE

.BR \-h ,
.B --help
.RS 4
Show usage information and exit.
.RE

.BR \-v ,
.B --version
.RS 4
Show version number and exit.
.RE


.SH EXAMPLE
Let us say that you want to manage the entries in
.IR /etc/hosts .
In such a case, you need to instruct
.B dotd
to manage the file and then you can add your own configuration fragments:

    dotd -t /etc/hosts || dotd -i /etc/hosts
    echo "1.1.1.1  hostname" >/etc/hosts.d/20-hostname
    dotd -u /etc/hosts

At this point, the file contains the original directives as well as the new one.


.SH REPORTING BUGS
If you encounter a bug, you should make sure that you are using the latest
version of the software. If you are and the bug is still present, you can
report it on the GitLab issues tracker:
.IR https://gitlab.com/vlastavesely/dotd/issues .


.SH LICENSE AND WARRANTY
Copyright © 2021  Vlasta Vesely <vlastavesely@protonmail.ch>

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 2 as published by the
Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
